// ============================================================
//  QUIZ BATTLE — QUESTIONS FILE
//  Easy to edit! Add new languages or questions here.
//
//  HOW TO ADD A NEW LANGUAGE:
//  Each question has a field for each language.
//  Currently: 'q' (question), 'a' (answer)
//  To add Arabic: add 'ar_q' and 'ar_a' fields
//  To add Turkish: add 'tr_q' and 'tr_a' fields
//
//  HOW TO ADD NEW QUESTIONS:
//  Just add a new object inside the array for that category.
//
//  QUESTION FORMATS:
//  vocab:     { q, a }
//  spelling:  { word, hint }
//  fillblank: { q, a, options: [4 choices] }
//  scramble:  { scrambled, answer, hint }
//  islamic:   { q, a, category: 'quran'|'hadith'|'history'|'pillars'|'terms' }
// ============================================================

module.exports = {

  // ── VOCABULARY ──────────────────────────────────────────────
  vocab: [
    { q: "What does 'benevolent' mean?", a: "Kind and generous" },
    { q: "What does 'eloquent' mean?", a: "Fluent and persuasive in speech" },
    { q: "What does 'meticulous' mean?", a: "Very careful and precise" },
    { q: "What does 'persevere' mean?", a: "To continue despite difficulty" },
    { q: "What does 'notorious' mean?", a: "Famous for something bad" },
    { q: "What does 'ambiguous' mean?", a: "Open to more than one interpretation" },
    { q: "What does 'resilient' mean?", a: "Able to recover quickly from difficulties" },
    { q: "What is a synonym for 'abundant'?", a: "Plentiful" },
    { q: "What is the antonym of 'cowardly'?", a: "Brave" },
    { q: "What is a synonym for 'melancholy'?", a: "Sad" },
    { q: "What does 'scrutinize' mean?", a: "To examine closely and carefully" },
    { q: "What does 'apprehensive' mean?", a: "Anxious or fearful about something" },
    { q: "What does 'contemplate' mean?", a: "To think deeply about something" },
    { q: "What does 'diligent' mean?", a: "Hard-working and careful" },
    { q: "What does 'eccentric' mean?", a: "Unusual or strange in behavior" },
    { q: "What does 'fabricate' mean?", a: "To invent a lie or make something up" },
    { q: "What does 'gratitude' mean?", a: "The feeling of being thankful" },
    { q: "What does 'hesitate' mean?", a: "To pause before doing something" },
    { q: "What does 'immense' mean?", a: "Extremely large or great" },
    { q: "What does 'justify' mean?", a: "To give a reason for something" },
    { q: "What does 'keen' mean?", a: "Eager or enthusiastic" },
    { q: "What does 'lenient' mean?", a: "Not strict, easy-going" },
    { q: "What does 'manipulate' mean?", a: "To control someone unfairly" },
    { q: "What does 'narrate' mean?", a: "To tell a story" },
    { q: "What does 'obscure' mean?", a: "Not well known or unclear" },
    { q: "What does 'pessimistic' mean?", a: "Expecting the worst to happen" },
    { q: "What does 'rational' mean?", a: "Based on reason and logic" },
    { q: "What does 'serene' mean?", a: "Calm and peaceful" },
    { q: "What does 'tedious' mean?", a: "Long, slow and boring" },
    { q: "What does 'vague' mean?", a: "Not clear or certain" },
    { q: "What does 'wary' mean?", a: "Cautious about possible danger" },
    { q: "What does 'yearn' mean?", a: "To have a strong desire for something" },
    { q: "What does 'zeal' mean?", a: "Great energy and enthusiasm" },
    { q: "What does 'adequate' mean?", a: "Enough or satisfactory" },
    { q: "What does 'candid' mean?", a: "Truthful and straightforward" },
    { q: "What does 'deduce' mean?", a: "To reach a conclusion by reasoning" },
    { q: "What does 'elaborate' mean?", a: "Detailed and complicated" },
    { q: "What does 'feeble' mean?", a: "Lacking strength or energy" },
    { q: "What does 'gloomy' mean?", a: "Dark or sad" },
    { q: "What does 'hinder' mean?", a: "To make it difficult to do something" },
    { q: "What does 'infer' mean?", a: "To conclude from evidence" },
    { q: "What does 'jovial' mean?", a: "Cheerful and friendly" },
    { q: "What is a synonym for 'courageous'?", a: "Brave" },
    { q: "What is a synonym for 'intelligent'?", a: "Smart" },
    { q: "What is the antonym of 'generous'?", a: "Stingy" },
    { q: "What is the antonym of 'ancient'?", a: "Modern" },
    { q: "What is the antonym of 'optimistic'?", a: "Pessimistic" },
    { q: "What is a synonym for 'hostile'?", a: "Aggressive" },
    { q: "What does 'blunt' mean?", a: "Direct and honest, not polite" },
    { q: "What does 'query' mean?", a: "A question or doubt" },
  ],

  // ── SPELLING BEE ─────────────────────────────────────────────
  spelling: [
    { word: "necessary", hint: "Required or needed" },
    { word: "accommodation", hint: "A place to stay" },
    { word: "embarrass", hint: "To make someone feel awkward" },
    { word: "conscience", hint: "Inner sense of right and wrong" },
    { word: "occurrence", hint: "An event or incident" },
    { word: "apparently", hint: "Seems to be true" },
    { word: "beginning", hint: "The start of something" },
    { word: "privilege", hint: "A special right or advantage" },
    { word: "recommend", hint: "To suggest something" },
    { word: "separate", hint: "To divide or keep apart" },
    { word: "definitely", hint: "Without any doubt" },
    { word: "environment", hint: "The natural world around us" },
    { word: "government", hint: "The group that rules a country" },
    { word: "independent", hint: "Not relying on others" },
    { word: "knowledge", hint: "Information and skills" },
    { word: "language", hint: "A system of communication" },
    { word: "mathematics", hint: "The study of numbers" },
    { word: "opportunity", hint: "A chance to do something" },
    { word: "responsible", hint: "Having a duty to do something" },
    { word: "successful", hint: "Having achieved a goal" },
    { word: "temperature", hint: "How hot or cold something is" },
    { word: "vocabulary", hint: "All the words you know" },
    { word: "Wednesday", hint: "The middle day of the week" },
    { word: "experience", hint: "Knowledge gained from doing things" },
    { word: "February", hint: "The shortest month of the year" },
    { word: "immediately", hint: "Right away without delay" },
    { word: "particularly", hint: "Especially or specifically" },
    { word: "receive", hint: "To get something given to you" },
    { word: "schedule", hint: "A plan of times for activities" },
    { word: "thoroughly", hint: "Completely and carefully" },
    { word: "vegetables", hint: "Plants we eat like carrots" },
    { word: "achievement", hint: "Something done successfully" },
    { word: "beautiful", hint: "Very pleasing to look at" },
    { word: "communicate", hint: "To share information with others" },
    { word: "discipline", hint: "Training to follow rules" },
    { word: "evidence", hint: "Facts that prove something" },
    { word: "fascinating", hint: "Extremely interesting" },
    { word: "guarantee", hint: "A promise that something will happen" },
    { word: "interesting", hint: "Holding your attention" },
    { word: "journalism", hint: "The work of writing news" },
    { word: "millennium", hint: "A period of one thousand years" },
    { word: "unnecessary", hint: "Not needed" },
    { word: "horizontal", hint: "Going from left to right" },
    { word: "lieutenant", hint: "A military officer rank" },
    { word: "parliament", hint: "A group of elected lawmakers" },
    { word: "questionnaire", hint: "A set of questions for research" },
    { word: "understand", hint: "To know the meaning of something" },
    { word: "jealousy", hint: "Feeling upset about someone else's success" },
    { word: "circumstances", hint: "The conditions affecting a situation" },
    { word: "perseverance", hint: "Continued effort despite difficulty" },
  ],

  // ── FILL IN THE BLANK ────────────────────────────────────────
  fillblank: [
    { q: "She has been studying English ___ two years.", a: "for", options: ["for","since","during","while"] },
    { q: "The news ___ very surprising yesterday.", a: "was", options: ["was","were","are","is"] },
    { q: "I wish I ___ more time to study.", a: "had", options: ["had","have","has","will have"] },
    { q: "Neither the students nor the teacher ___ ready.", a: "was", options: ["was","were","are","is"] },
    { q: "By next year, she ___ finished her studies.", a: "will have", options: ["will have","would have","had","has"] },
    { q: "They suggested that he ___ the doctor.", a: "see", options: ["see","sees","saw","seen"] },
    { q: "I have lived here ___ 2010.", a: "since", options: ["since","for","during","from"] },
    { q: "He is good ___ playing football.", a: "at", options: ["at","in","on","for"] },
    { q: "She arrived ___ the airport two hours early.", a: "at", options: ["at","in","to","on"] },
    { q: "We are looking forward ___ meeting you.", a: "to", options: ["to","for","at","of"] },
    { q: "If it ___ tomorrow, we will cancel the trip.", a: "rains", options: ["rains","rained","rain","will rain"] },
    { q: "He would have passed if he ___ harder.", a: "had studied", options: ["had studied","studied","has studied","would study"] },
    { q: "I am interested ___ learning new languages.", a: "in", options: ["in","at","on","for"] },
    { q: "They have known each other ___ they were children.", a: "since", options: ["since","for","when","during"] },
    { q: "The teacher asked us ___ our books.", a: "to open", options: ["to open","open","opening","opened"] },
    { q: "She is ___ tallest girl in the class.", a: "the", options: ["the","a","an","—"] },
    { q: "We should ___ more water every day.", a: "drink", options: ["drink","drinking","drinks","to drink"] },
    { q: "My friend ___ in London since last year.", a: "has lived", options: ["has lived","lived","is living","lives"] },
    { q: "He is afraid ___ spiders.", a: "of", options: ["of","from","about","with"] },
    { q: "___ she was tired, she continued working.", a: "Although", options: ["Although","Because","So","If"] },
    { q: "I would rather ___ at home than go out.", a: "stay", options: ["stay","to stay","staying","stayed"] },
    { q: "He has been working here ___ five years.", a: "for", options: ["for","since","during","from"] },
    { q: "She apologized ___ being late.", a: "for", options: ["for","about","of","to"] },
    { q: "This bag is not ___ heavy for me to carry.", a: "too", options: ["too","so","such","very"] },
    { q: "I wish I ___ harder last year.", a: "had worked", options: ["had worked","worked","have worked","would work"] },
    { q: "The film is based ___ a true story.", a: "on", options: ["on","in","at","of"] },
    { q: "They prevented us ___ entering the building.", a: "from", options: ["from","of","about","to"] },
    { q: "He is used to ___ up early every morning.", a: "waking", options: ["waking","wake","wakes","woke"] },
    { q: "I don't mind ___ for you if you are late.", a: "waiting", options: ["waiting","wait","to wait","waited"] },
    { q: "He succeeded ___ passing the exam.", a: "in", options: ["in","at","on","with"] },
    { q: "She ___ to be very shy when she was young.", a: "used", options: ["used","was used","is used","would"] },
    { q: "The more you practice, ___ you become.", a: "the better", options: ["the better","better","the best","best"] },
    { q: "She had barely sat down ___ the phone rang.", a: "when", options: ["when","than","after","before"] },
    { q: "It is no use ___ over spilled milk.", a: "crying", options: ["crying","cry","to cry","cried"] },
    { q: "I ___ rather have tea than coffee.", a: "would", options: ["would","will","should","could"] },
    { q: "Neither of them ___ the answer.", a: "knew", options: ["knew","know","knows","known"] },
    { q: "The exam ___ at 9 AM tomorrow.", a: "starts", options: ["starts","start","is starting","started"] },
    { q: "I ___ to the gym three times a week.", a: "go", options: ["go","goes","going","went"] },
    { q: "He ___ to school on foot every morning.", a: "walks", options: ["walks","walk","is walking","walked"] },
    { q: "By the time he arrived, the party ___.", a: "had ended", options: ["had ended","ended","has ended","was ending"] },
  ],

  // ── WORD SCRAMBLE ────────────────────────────────────────────
  scramble: [
    { scrambled: "PHALYP", answer: "HAPPY", hint: "Feeling of joy" },
    { scrambled: "LECHANLEG", answer: "CHALLENGE", hint: "A difficult task" },
    { scrambled: "WKEDGONLE", answer: "KNOWLEDGE", hint: "Information and skills" },
    { scrambled: "RETFEP", answer: "PERFECT", hint: "Without any flaws" },
    { scrambled: "DNFREID", answer: "FRIEND", hint: "A person you like and trust" },
    { scrambled: "YELBIVE", answer: "BELIEVE", hint: "To think something is true" },
    { scrambled: "GLNUAGEA", answer: "LANGUAGE", hint: "A system of communication" },
    { scrambled: "ECCSUS", answer: "SUCCESS", hint: "Achieving a goal" },
    { scrambled: "TULBAEIFUN", answer: "BEAUTIFUL", hint: "Very pleasing to look at" },
    { scrambled: "NDEEFIFCNO", answer: "CONFIDENCE", hint: "Belief in yourself" },
    { scrambled: "TCPESER", answer: "RESPECT", hint: "To treat others with care" },
    { scrambled: "EDROUMF", answer: "FREEDOM", hint: "The right to do what you want" },
    { scrambled: "NRIWTG", answer: "WRITING", hint: "Putting words on paper" },
    { scrambled: "RDIENAGT", answer: "READING", hint: "Looking at words and understanding them" },
    { scrambled: "RMEOMYE", answer: "MEMORY", hint: "The ability to remember things" },
    { scrambled: "ICTCAEVR", answer: "CREATIVE", hint: "Having new and original ideas" },
    { scrambled: "LAYTYL", answer: "LOYALTY", hint: "Being faithful to someone" },
    { scrambled: "EARTBCE", answer: "CELEBRATE", hint: "To do something special for an event" },
    { scrambled: "EGRUOCANE", answer: "ENCOURAGE", hint: "To give someone confidence" },
    { scrambled: "TSEERSPIN", answer: "PERSISTENT", hint: "Continuing despite difficulty" },
    { scrambled: "LBSVAUAE", answer: "VALUABLE", hint: "Worth a lot or important" },
    { scrambled: "RITNEFED", answer: "DIFFERENT", hint: "Not the same as something else" },
    { scrambled: "IECNTIS", answer: "SCIENCE", hint: "The study of the natural world" },
    { scrambled: "DLENWOF", answer: "WONDERFUL", hint: "Extremely good or impressive" },
    { scrambled: "LNICEEVL", answer: "EXCELLENCE", hint: "The quality of being very good" },
    { scrambled: "TSEIFAV", answer: "FESTIVAL", hint: "A special celebration or event" },
    { scrambled: "INONATIMI", answer: "IMAGINATION", hint: "Forming pictures in your mind" },
    { scrambled: "YVIITARECT", answer: "CREATIVITY", hint: "The use of imagination to create" },
    { scrambled: "TNAELCT", answer: "TALENTED", hint: "Having a natural ability" },
    { scrambled: "TICPRAEC", answer: "PRACTICE", hint: "Doing something repeatedly to improve" },
    { scrambled: "DGRENA", answer: "DANGER", hint: "Possibility of harm" },
    { scrambled: "ECTLURE", answer: "LECTURE", hint: "A talk given to students" },
    { scrambled: "EPSDNIT", answer: "INSPIRED", hint: "Feeling motivated to create" },
    { scrambled: "YIRTCOS", answer: "VICTORY", hint: "Winning a competition" },
    { scrambled: "ECDVANIE", answer: "EVIDENCE", hint: "Facts that prove something" },
    { scrambled: "MREYSJOU", answer: "JOURNEY", hint: "A long trip" },
    { scrambled: "ELAGRN", answer: "LEARNER", hint: "Someone who is learning" },
    { scrambled: "RCTAHACER", answer: "CHARACTER", hint: "Qualities that make a person who they are" },
    { scrambled: "YTXNEIA", answer: "ANXIETY", hint: "Feeling worried and nervous" },
    { scrambled: "BLUPICH", answer: "REPUBLIC", hint: "A type of government" },
  ],

  // ── ISLAMIC QUIZ ─────────────────────────────────────────────
  // FORMAT: { q, a, category }
  // CATEGORIES: quran | hadith | history | pillars | terms
  // TO ADD MORE QUESTIONS: just add a new line below following the same format
  // TO ADD ARABIC: add  ar_q: "Arabic question", ar_a: "Arabic answer"
  // TO ADD TURKISH: add tr_q: "Turkish question", tr_a: "Turkish answer"
  islamic: [

    // ── Quran ──────────────────────────────────────────────────
    { q: "How many Surahs (chapters) are in the Holy Quran?", a: "114 Surahs", category: "quran" },
    { q: "What is the first Surah of the Quran?", a: "Al-Fatiha (The Opening)", category: "quran" },
    { q: "What is the last Surah of the Quran?", a: "An-Nas (Mankind)", category: "quran" },
    { q: "What is the longest Surah in the Quran?", a: "Al-Baqarah (The Cow)", category: "quran" },
    { q: "What is the shortest Surah in the Quran?", a: "Al-Kawthar", category: "quran" },
    { q: "How many Juz (parts) does the Quran have?", a: "30 Juz", category: "quran" },
    { q: "In which month was the Quran first revealed?", a: "Ramadan", category: "quran" },
    { q: "What does 'Ayah' mean?", a: "A verse of the Quran", category: "quran" },
    { q: "What is the Surah of the Heart of the Quran?", a: "Surah Ya-Sin (Ya-Seen)", category: "quran" },
    { q: "Which Surah is known as the 'Throne Verse'?", a: "Ayatul Kursi in Surah Al-Baqarah", category: "quran" },
    { q: "How many times is the word 'Allah' mentioned in the Quran?", a: "2698 times", category: "quran" },
    { q: "Which Prophet is mentioned the most times in the Quran?", a: "Prophet Musa (Moses)", category: "quran" },
    { q: "What is the meaning of 'Quran'?", a: "That which is recited / The Recitation", category: "quran" },
    { q: "In which city was the Quran first revealed?", a: "Makkah (Mecca)", category: "quran" },
    { q: "Which angel brought the revelation to Prophet Muhammad ﷺ?", a: "Angel Jibreel (Gabriel)", category: "quran" },

    // ── Hadith & Sunnah ────────────────────────────────────────
    { q: "What does 'Hadith' mean?", a: "A saying, action or approval of Prophet Muhammad ﷺ", category: "hadith" },
    { q: "What is the most authentic collection of Hadith?", a: "Sahih Al-Bukhari", category: "hadith" },
    { q: "What does 'Sunnah' mean?", a: "The way and practices of Prophet Muhammad ﷺ", category: "hadith" },
    { q: "According to Hadith, what are the rights of a Muslim over another?", a: "Greeting with Salam, visiting when sick, attending funeral, accepting invitation, saying Yarhamukallah when sneezing", category: "hadith" },
    { q: "What is the Hadith about actions?", a: "Actions are judged by intentions (Innama al-a'malu bin-niyyat)", category: "hadith" },
    { q: "What does the Hadith say about smiling?", a: "Smiling at your brother is an act of charity (Sadaqah)", category: "hadith" },
    { q: "According to Hadith, what is the best Jihad?", a: "Speaking the truth in front of an unjust ruler", category: "hadith" },
    { q: "What are the six books of Hadith called?", a: "The Kutub al-Sittah (Six Major Hadith Collections)", category: "hadith" },
    { q: "According to Hadith, which prayer is equivalent to praying all night?", a: "Isha prayer in congregation", category: "hadith" },
    { q: "What does the Prophet ﷺ say about cleanliness?", a: "Cleanliness is half of faith (Taharah is half of Iman)", category: "hadith" },

    // ── Islamic History & Prophets ─────────────────────────────
    { q: "Who was the first Prophet of Islam?", a: "Prophet Adam (AS)", category: "history" },
    { q: "Who was the last Prophet of Islam?", a: "Prophet Muhammad ﷺ", category: "history" },
    { q: "In which city was Prophet Muhammad ﷺ born?", a: "Makkah (Mecca)", category: "history" },
    { q: "What year was Prophet Muhammad ﷺ born?", a: "570 CE (Year of the Elephant)", category: "history" },
    { q: "What is the Hijra?", a: "The migration of Prophet Muhammad ﷺ from Makkah to Madinah", category: "history" },
    { q: "Who was the first Caliph of Islam?", a: "Abu Bakr As-Siddiq (RA)", category: "history" },
    { q: "How many prophets are mentioned in the Quran?", a: "25 Prophets", category: "history" },
    { q: "Who built the Kaaba originally?", a: "Prophet Ibrahim (AS) and his son Ismail (AS)", category: "history" },
    { q: "What is the Battle of Badr?", a: "The first major battle in Islam, fought in 624 CE", category: "history" },
    { q: "Who was the wife of Prophet Muhammad ﷺ who was first to accept Islam?", a: "Khadijah (RA)", category: "history" },
    { q: "What is the significance of Laylatul Qadr?", a: "The Night of Power, better than 1000 months, when the Quran was first revealed", category: "history" },
    { q: "Which Prophet was known as Khalilullah (Friend of Allah)?", a: "Prophet Ibrahim (AS)", category: "history" },
    { q: "Which Prophet could speak to birds and animals?", a: "Prophet Sulaiman (Solomon) AS", category: "history" },
    { q: "What is the Isra and Miraj?", a: "The Night Journey and Ascension of Prophet Muhammad ﷺ to the heavens", category: "history" },
    { q: "Who was the companion known as the 'Sword of Allah'?", a: "Khalid ibn al-Walid (RA)", category: "history" },

    // ── Pillars of Islam & Iman ────────────────────────────────
    { q: "How many Pillars of Islam are there?", a: "5 Pillars", category: "pillars" },
    { q: "What is the first Pillar of Islam?", a: "Shahada — Declaration of Faith", category: "pillars" },
    { q: "What is the second Pillar of Islam?", a: "Salah — The 5 Daily Prayers", category: "pillars" },
    { q: "What is the third Pillar of Islam?", a: "Zakat — Obligatory Charity", category: "pillars" },
    { q: "What is the fourth Pillar of Islam?", a: "Sawm — Fasting in Ramadan", category: "pillars" },
    { q: "What is the fifth Pillar of Islam?", a: "Hajj — Pilgrimage to Makkah", category: "pillars" },
    { q: "How many Pillars of Iman (Faith) are there?", a: "6 Pillars", category: "pillars" },
    { q: "What are the 6 Pillars of Iman?", a: "Belief in Allah, Angels, Books, Prophets, Day of Judgment, Divine Decree (Qadar)", category: "pillars" },
    { q: "How many times a day do Muslims pray?", a: "5 times a day", category: "pillars" },
    { q: "What percentage of wealth is given as Zakat?", a: "2.5% of savings held for one year", category: "pillars" },
    { q: "Who must perform Hajj?", a: "Every Muslim who is physically and financially able, once in a lifetime", category: "pillars" },
    { q: "What is the Shahada?", a: "La ilaha illallah, Muhammadur Rasulullah — There is no god but Allah, Muhammad is His Messenger", category: "pillars" },
    { q: "What is Salatul Fajr?", a: "The dawn prayer — first of the 5 daily prayers", category: "pillars" },
    { q: "What direction do Muslims face when praying?", a: "Toward the Qibla (Kaaba in Makkah)", category: "pillars" },
    { q: "What is the night prayer called?", a: "Isha — the 5th and last daily prayer", category: "pillars" },

    // ── Islamic Terms ──────────────────────────────────────────
    { q: "What does 'Islam' mean?", a: "Submission / Peace / Surrender to the will of Allah", category: "terms" },
    { q: "What does 'Muslim' mean?", a: "One who submits to the will of Allah", category: "terms" },
    { q: "What does 'Alhamdulillah' mean?", a: "All praise is due to Allah", category: "terms" },
    { q: "What does 'Inshallah' mean?", a: "If Allah wills / God willing", category: "terms" },
    { q: "What does 'Subhanallah' mean?", a: "Glory be to Allah", category: "terms" },
    { q: "What does 'Allahu Akbar' mean?", a: "Allah is the Greatest", category: "terms" },
    { q: "What does 'Assalamu Alaikum' mean?", a: "Peace be upon you", category: "terms" },
    { q: "What does 'Bismillah' mean?", a: "In the name of Allah", category: "terms" },
    { q: "What does 'Tawbah' mean?", a: "Repentance — turning back to Allah", category: "terms" },
    { q: "What does 'Tawakkul' mean?", a: "Complete trust and reliance on Allah", category: "terms" },
    { q: "What does 'Ummah' mean?", a: "The global community of Muslims", category: "terms" },
    { q: "What does 'Halal' mean?", a: "Permissible according to Islamic law", category: "terms" },
    { q: "What does 'Haram' mean?", a: "Forbidden according to Islamic law", category: "terms" },
    { q: "What does 'Dua' mean?", a: "Supplication — asking Allah directly", category: "terms" },
    { q: "What does 'Taqwa' mean?", a: "God-consciousness / Fear and awareness of Allah", category: "terms" },
    { q: "What does 'Sadaqah' mean?", a: "Voluntary charity given for the sake of Allah", category: "terms" },
    { q: "What does 'Masjid' mean?", a: "Mosque — a place of prostration and worship", category: "terms" },
    { q: "What does 'Iman' mean?", a: "Faith / Belief in Islam", category: "terms" },
    { q: "What does 'Jihad' mean?", a: "Striving and struggling in the way of Allah", category: "terms" },
    { q: "What does 'Wudu' mean?", a: "Ritual purification / ablution before prayer", category: "terms" },
  ],

};
